services:
  db_02:
    image: postgres:13
    restart: always
    env_file:
      - .env 
    ports:
      - '5434:5432'
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    volumes: 
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    driver: local